### ISSUE TITLE
trying to access a variable that doesnt exist with an external command causes a python error

### ISSUE THREAD

**Issue by Butterroach** [slashsh/slash#3]
![image](https://github.com/slashsh/slash/assets/111113093/834d1f67-0a42-446f-ab28-319b5d7dd9c3)

**Comment by Butterroach** [comment]
first bug!!!!!!!!!!!!!!!!!!!!!!!!!!!! dogfooding is the only reason i discovered this

**Comment by Butterroach** [comment]
@OcaMinty you are not at all in this org and you definitely do not know how to do anything in this code base nor is this your fault at all but fuck you fix it for me

**Comment by OcaMinty** [comment]
Aight

**Comment by Butterroach** [comment]
i forgot to put a `continue` statement ![laughing emoji person on the ground](https://cdn.discordapp.com/emojis/921382638407811094.webp?size=44&quality=lossless)
